### PR TITLE
Data visualisation

### LINKED ISSUE #3: Data visualisation (boxplot, correlation matrix etc.)

### PR DESCRIPTION
**Pull request by Zoey-2024**
Resolves #3

### CODE REVIEW

**Review by Yunfei-Ch — APPROVED** [review]
It looks like it has a lot of outlier

**Review by shuyin1013 — COMMENTED** [review]
It seems that the correlation among 'aroma', 'flavor', and 'acidity' is very strong.

**Review by 1162259403WXR — APPROVED** [review]
That's so cool！Based on the scatterplot matrix I can see that the correlation between the first three variables is large, so I think we need to do principal component analysis to reduce the multicollinearity.

**Review by shuyin1013 — APPROVED** [review]

**Review by Gu-YuxuanLi — APPROVED** [review]
According to this boxplot, I can know that there are many outliers. We might be able to delete the 0. This may be caused by a recording error.

**Comment by Zoey-2024** [comment]
Okay I will merge this to main

**Pull request merged**
